[workspace]
name = "lineremovernn"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
cairo = "*"
cmake = "*"
compilers = "*"
expat = "*"
opencv = ">=4.0.0,<5.0.0"
pkg-config = "*"
zlib = "*"
pre-commit = ">=4.6.2,<5"

[pypi-dependencies]
lineremovernn = { path = ".", editable = true }
scikit-build-core = ">=0.12.2"
nanobind = ">=2.0"

[tasks]
build = "uv pip install --no-build-isolation --no-deps -e ."
lineremovernn = { cmd = "lineremovernn", depends-on = ["build"] }
dev = { cmd = "lineremovernn", depends-on = ["build"] }
hooks = "uv run pre-commit install"
link-compile-commands = "ln -sf build/compile_commands.json compile_commands.json"
clangd-setup = { cmd = "pixi run link-compile-commands", depends-on = ["build"] }
